libname LIB 'C:\ECLSK2011 K5PUF\';

filename in1 'C:\childK5p.dat';

footnote 'C:\ECLSK2011 K5PUF\Variables used.sas';

proc format; 
   value X12RACTH
      1 = "1: WHITE, NON-HISPANIC"
      2 = "2: BLACK/AFRICAN AMERICAN, NON-HISPANIC"
      3 = "3: HISPANIC, RACE SPECIFIED"
      4 = "4: HISPANIC, NO RACE SPECIFIED"
      5 = "5: ASIAN, NON-HISPANIC"
      6 = "6: NATIVE HAWAIIAN/PACIFIC ISLANDER, NON-HISPANIC"
      7 = "7: AMERICAN INDIAN/ALASKA NATIVE, NON-HISPANIC"
      8 = "8: TWO OR MORE RACES, NON-HISPANIC"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X1KSCTYP
      1 = "1: CATHOLIC"
      2 = "2: OTHER RELIGIOUS"
      3 = "3: OTHER PRIVATE"
      4 = "4: PUBLIC"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X1PUBPRI
      1 = "1: PUBLIC"
      2 = "2: PRIVATE"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X1RDGFLG
      0 = "0: FALSE"
      1 = "1: TRUE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X2KSCTYP
      1 = "1: CATHOLIC"
      2 = "2: OTHER RELIGIOUS"
      3 = "3: OTHER PRIVATE"
      4 = "4: PUBLIC"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X2PUBPRI
      1 = "1: PUBLIC"
      2 = "2: PRIVATE"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X4PUBPRI
      1 = "1: PUBLIC"
      2 = "2: PRIVATE"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X_CHSEX
      1 = "1: MALE"
      2 = "2: FEMALE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value X_DOBMM
      1 = "1: JANUARY"
      2 = "2: FEBRUARY"
      3 = "3: MARCH"
      4 = "4: APRIL"
      5 = "5: MAY"
      6 = "6: JUNE"
      7 = "7: JULY"
      8 = "8: AUGUST"
      9 = "9: SEPTEMBER"
      10 = "10: OCTOBER"
      11 = "11: NOVEMBER"
      12 = "12: DECEMBER"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value _9F
      -9 = "-9: NOT ASCERTAINED"
   ;
   value $PUF300F
      "-2" = "-2: DATA SUPPRESSED"
   ;
   value $LINKMF
      "M01" = "M01"
      "M02" = "M02"
      "M03" = "M03"
      "M04" = "M04"
      "M05" = "M05"
   ;
   value PUF129F
      1 = "1: 2003/2004"
      2 = "2: 2005/2006"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value PUF130F
      1 = "1: CITY(11, 12, 13)"
      2 = "2: SUBURB (21, 22, 23)"
      3 = "3: TOWN (31, 32, 33)"
      4 = "4: RURAL (41, 42, 43)"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value PUF132F
      1 = "1: CITY(11, 12, 13)"
      2 = "2: SUBURB (21, 22, 23)"
      3 = "3: TOWN (31, 32, 33)"
      4 = "4: RURAL (41, 42, 43)"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value PUF134F
      1 = "1: CITY(11, 12, 13)"
      2 = "2: SUBURB (21, 22, 23)"
      3 = "3: TOWN (31, 32, 33)"
      4 = "4: RURAL (41, 42, 43)"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value PUF137F
      1 = "1: CITY (11, 12, 13)"
      2 = "2: SUBURB (21, 22, 23)"
      3 = "3: TOWN (31, 32, 33)"
      4 = "4: RURAL (41, 42, 43)"
      -1 = "-1: NOT APPLICABLE"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value PUF146F
      -2 = "-2: DATA SUPPRESSED"
   ;
   value PUF242F
      1 = "1: ASSESSED"
      2 = "2: EXCLUDED DUE TO DISABILITY OR NO ASSESSMENT"
      -9 = "-9: NOT ASCERTAINED"
   ;
   value $LINKR9F
      "R01" = "R01"
      "R02" = "R02"
      "R03" = "R03"
      "R04" = "R04"
      "R05" = "R05"
      "R06" = "R06"
      "R07" = "R07"
   ;
   value $LINKS9F
      "S01" = "S01"
      "S02" = "S02"
      "S03" = "S03"
      "S04" = "S04"
      "S05" = "S05"
      "S06" = "S06"
   ;
   value X9OUTLIER
      0 = "0: FALSE"
      1 = "1: TRUE"
   ;

run;

data lib.Variables used;
   infile in1 lrecl=5009 n=27;
      input 
   #1
      @1 CHILDID $8.
      @9 PARENTID $8.
      @17 PSUID $7.
      @24 S1_ID $4.
      @28 S2_ID $4.
      @32 S3_ID $4.
      @36 S4_ID $4.
      @40 S5_ID $4.
      @44 S6_ID $4.
      @48 S7_ID $4.
      @52 S8_ID $4.
      @56 S9_ID $4.
      @60 T1_ID $7.
      @67 T2_ID $7.
      @74 T3_ID $7.
      @81 T4_ID $7.
      @88 T5_ID 7.
      @95 T6_ID 7.
      @102 T7_ID 7.
      @109 T8R_ID 7.
      @116 T8RCLASS $3.
      @119 T8M_ID 7.
      @126 T8MCLASS $3.
      @129 T8S_ID 7.
      @136 T8SCLASS $3.
      @139 T9R_ID 7.
      @146 T9RCLASS $3.
      @149 T9M_ID 7.
      @156 T9MCLASS $3.
      @159 T9S_ID 7.
      @166 T9SCLASS $3.
      @169 D2T_ID $7.
      @176 D4T_ID $7.
      @183 D6T_ID 7.
      @190 D7T_ID 7.
      @197 D8T_ID 7.
      @204 D9T_ID 7.
      @211 CC_ID $8.
      @219 TWIN_ID $8.
      @1473 X9RDGFLG 2.
      @1483 X9RTOFLG 1.
      @1690 X9RSCALK5 8.4
      @1714 X9MTHFLG 2.
      @1724 X9MTOFLG 1.
      @1931 X9MSCALK5 8.4
      @1953 X9SCIFLG 2.
      @1962 X9STOFLG 1.
      @2145 X9SSCALK5 8.4
      @2907 X9TCHAPP 6.4
      @2981 X9TCHCON 6.4
      @3041 X9TCHPER 6.2
      @3109 X9TCHEXT 6.4
      @3183 X9TCHINT 6.4
      @3245 X9ATTMCQ 8.4
      @3309 X9INTMCQ 8.4
      @3549 X9EXDIS 2.
      @3759 X_CHSEX_R 2.
      @3761 X_DOBMM_R 2.
      @3763 X_DOBYY_R 4.
      @3781 X_RACETH_R 2.
      @3817 X1LOCALE 2.
      @3819 X2LOCALE 2.
      @3821 X3LOCALE 2.
      @3823 X4LOCALE 2.
      @3825 X5LOCALE 2.
      @3827 X6LOCALE 2.
      @3829 X7LOCALE 2.
      @3831 X8LOCALE 2.
      @3833 X9LOCALE 2.
      @3835 X1REGION 2.
      @3837 X2REGION 2.
      @3839 X3REGION 2.
      @3841 X4REGION 2.
      @3843 X5REGION 2.
      @3845 X6REGION 2.
      @3847 X7REGION 2.
      @3849 X8REGION 2.
      @3851 X9REGION 2.
      @4469 X9SESL_I 7.4
      @4492 X1PUBPRI 2.
      @4494 X2PUBPRI 2.
      @4496 X3PUBPRI 2.
      @4498 X4PUBPRI 2.
      @4500 X5PUBPRI 2.
      @4502 X6PUBPRI 2.
      @4504 X7PUBPRI 2.
      @4506 X8PUBPRI 2.
      @4508 X9PUBPRI 2.
      @4510 X1KSCTYP 2.
      @4512 X2KSCTYP 2.
      @4514 X4SCTYP 2.
      @4516 X6SCTYP 2.
      @4518 X7SCTYP 2.
      @4520 X8SCTYP 2.
      @4522 X9SCTYP 2.
      @4783 X9ASMTST 2.
   #27
      ;

   IF (X1PUBPRI EQ 1 OR 
       X1PUBPRI EQ 2 OR 
       X1PUBPRI EQ -1 OR 
       X1PUBPRI EQ -9 OR 
       X1PUBPRI EQ .) AND 
      (X2PUBPRI EQ 1 OR 
       X2PUBPRI EQ 2 OR 
       X2PUBPRI EQ -1 OR 
       X2PUBPRI EQ -9) AND 
      (X3PUBPRI EQ 1 OR 
       X3PUBPRI EQ 2 OR 
       X3PUBPRI EQ -1 OR 
       X3PUBPRI EQ -9 OR 
       X3PUBPRI EQ .) AND 
      (X4PUBPRI EQ 1 OR 
       X4PUBPRI EQ 2 OR 
       X4PUBPRI EQ -1 OR 
       X4PUBPRI EQ -9 OR 
       X4PUBPRI EQ .) AND 
      (X5PUBPRI EQ 1 OR 
       X5PUBPRI EQ 2 OR 
       X5PUBPRI EQ -1 OR 
       X5PUBPRI EQ -9 OR 
       X5PUBPRI EQ .) AND 
      (X6PUBPRI EQ 1 OR 
       X6PUBPRI EQ 2 OR 
       X6PUBPRI EQ -1 OR 
       X6PUBPRI EQ -9 OR 
       X6PUBPRI EQ .) AND 
      (X7PUBPRI EQ 1 OR 
       X7PUBPRI EQ 2 OR 
       X7PUBPRI EQ -1 OR 
       X7PUBPRI EQ -9 OR 
       X7PUBPRI EQ .) AND 
      (X8PUBPRI EQ 1 OR 
       X8PUBPRI EQ 2 OR 
       X8PUBPRI EQ -1 OR 
       X8PUBPRI EQ -9 OR 
       X8PUBPRI EQ .) AND 
      (X9PUBPRI EQ 1 OR 
       X9PUBPRI EQ 2 OR 
       X9PUBPRI EQ -1 OR 
       X9PUBPRI EQ -9 OR 
       X9PUBPRI EQ .) AND 
      (X1KSCTYP EQ 1 OR 
       X1KSCTYP EQ 2 OR 
       X1KSCTYP EQ 3 OR 
       X1KSCTYP EQ 4 OR 
       X1KSCTYP EQ -1 OR 
       X1KSCTYP EQ -9 OR 
       X1KSCTYP EQ .) AND 
      (X2KSCTYP EQ 1 OR 
       X2KSCTYP EQ 2 OR 
       X2KSCTYP EQ 3 OR 
       X2KSCTYP EQ 4 OR 
       X2KSCTYP EQ -1 OR 
       X2KSCTYP EQ -9) AND 
      (X4SCTYP EQ 1 OR 
       X4SCTYP EQ 2 OR 
       X4SCTYP EQ 3 OR 
       X4SCTYP EQ 4 OR 
       X4SCTYP EQ -1 OR 
       X4SCTYP EQ -9 OR 
       X4SCTYP EQ .) AND 
      (X6SCTYP EQ 1 OR 
       X6SCTYP EQ 2 OR 
       X6SCTYP EQ 3 OR 
       X6SCTYP EQ 4 OR 
       X6SCTYP EQ -1 OR 
       X6SCTYP EQ -9 OR 
       X6SCTYP EQ .) AND 
      (X7SCTYP EQ 1 OR 
       X7SCTYP EQ 2 OR 
       X7SCTYP EQ 3 OR 
       X7SCTYP EQ 4 OR 
       X7SCTYP EQ -1 OR 
       X7SCTYP EQ -9 OR 
       X7SCTYP EQ .) AND 
      (X8SCTYP EQ 1 OR 
       X8SCTYP EQ 2 OR 
       X8SCTYP EQ 3 OR 
       X8SCTYP EQ 4 OR 
       X8SCTYP EQ -1 OR 
       X8SCTYP EQ -9 OR 
       X8SCTYP EQ .) AND 
      (X9SCTYP EQ 1 OR 
       X9SCTYP EQ 2 OR 
       X9SCTYP EQ 3 OR 
       X9SCTYP EQ 4 OR 
       X9SCTYP EQ -1 OR 
       X9SCTYP EQ -9 OR 
       X9SCTYP EQ .);

   label
      CHILDID = "CHILD IDENTIFICATION NUMBER"
      PARENTID = "PARENT IDENTIFICATION NUMBER"
      PSUID = "ORIGINAL SAMPLED PSU ID"
      S1_ID = "FALL 2010 SCHOOL IDENTIFICATION NUMBER"
      S2_ID = "SPRING 2011 SCHOOL IDENTIFICATION NUMBER"
      S3_ID = "FALL 2011 SCHOOL IDENTIFICATION NUMBER"
      S4_ID = "SPRING 2012 SCHOOL IDENTIFICATION NUMBER"
      S5_ID = "FALL 2012 SCHOOL IDENTIFICATION NUMBER"
      S6_ID = "SPRING 2013 SCHOOL IDENTIFICATION NUMBER"
      S7_ID = "SPRING 2014 SCHOOL IDENTIFICATION NUMBER"
      S8_ID = "SPRING 2015 SCHOOL IDENTIFICATION NUMBER"
      S9_ID = "SPRING 2016 SCHOOL IDENTIFICATION NUMBER"
      T1_ID = "FALL 2010 TEACHER IDENTIFICATION NUMBER"
      T2_ID = "SPRING 2011 TEACHER IDENTIFICATION NUMB"
      T3_ID = "FALL 2011 TEACHER IDENTIFICATION NUMBER"
      T4_ID = "SPRING 2012 TEACHER IDENTIFICATION NUMBER"
      T5_ID = "FALL 2012 TEACHER IDENTIFICATION NUMBER"
      T6_ID = "SPRING 2013 TEACHER IDENTIFICATION NUMBER"
      T7_ID = "SPRING 2014 TEACHER IDENTIFICATION NUMBER"
      T8R_ID = "SPRING 2015 READING TEACHER IDENTIFICATION NUMBER"
      T8RCLASS = "SPRING 2015 READING TEACHER CLASS LINK ID"
      T8M_ID = "SPRING 2015 MATH TEACHER IDENTIFICATION NUMBER"
      T8MCLASS = "SPRING 2015 MATH TEACHER CLASS LINK ID"
      T8S_ID = "SPRING 2015 SCIENCE TEACHER IDENTIFICATION NUMBER"
      T8SCLASS = "SPRING 2015 SCIENCE TEACHER CLASS LINK ID"
      T9R_ID = "SPRING 2016 READING TEACHER IDENTIFICATION NUMBER"
      T9RCLASS = "SPRING 2016 READING TEACHER CLASS LINK ID"
      T9M_ID = "SPRING 2016 MATH TEACHER IDENTIFICATION NUMBER"
      T9MCLASS = "SPRING 2016 MATH TEACHER CLASS LINK ID"
      T9S_ID = "SPRING 2016 SCIENCE TEACHER IDENTIFICATION NUMBER"
      T9SCLASS = "SPRING 2016 SCIENCE TEACHER CLASS LINK ID"
      D2T_ID = "SPRING 2011 SPECIAL ED TEACHER ID NUMBER"
      D4T_ID = "SPRING 2012 SPECIAL ED TEACHER ID NUMBER"
      D6T_ID = "SPRING 2013 SPECIAL ED TEACHER ID NUMBER"
      D7T_ID = "SPRING 2014 SPECIAL ED TEACHER ID NUMBER"
      D8T_ID = "SPRING 2015 SPECIAL ED TEACHER ID NUMBER"
      D9T_ID = "SPRING 2016 SPECIAL ED TEACHER ID NUMBER"
      CC_ID = "CHILD CARE PROVIDER IDENTIFICATION NUM"
      TWIN_ID = "CHILDID FOR FOCAL CHILD'S TWIN"
      X9RDGFLG = "X9 READING TEST SCORE PRESENT"
      X9RTOFLG = "X9 READING THETA IS AN OUTLIER"
      X9RSCALK5 = "X9 READING IRT SCALE SCORE-K5 DATA FILE"
      X9MTHFLG = "X9 MATH TEST SCORE PRESENT"
      X9MTOFLG = "X9 MATH THETA IS AN OUTLIER"
      X9MSCALK5 = "X9 MATH IRT SCALE SCORE-K5 DATA FILE"
      X9SCIFLG = "X9 SCIENCE TEST SCORE PRESENT"
      X9STOFLG = "X9 SCIENCE THETA IS AN OUTLIER"
      X9SSCALK5 = "X9 SCIENCE IRT SCALE SCORE-K5 DATA FILE"
      X9TCHAPP = "X9 TEACHER REPORT APPROACHES TO LEARNING"
      X9TCHCON = "X9 TEACHER REPORT SELF-CONTROL"
      X9TCHPER = "X9 TEACHER REPORT INTERPERSONAL"
      X9TCHEXT = "X9 TEACHER REPORT EXTERN PROB BEHAVIORS"
      X9TCHINT = "X9 TEACHER REPORT INTERN PROB BEHAVIORS"
      X9ATTMCQ = "X9 TMCQ TEACHER REPORT ATTENTIONAL FOCUS"
      X9INTMCQ = "X9 TMCQ TEACHER REPRT INHIBITORY CONTROL"
      X9EXDIS = "X9 CHILD NOT ASSESSED - DISAB EXCLUSION"
      X_CHSEX_R = "CHILD COMPOSITE SEX - REVISED"
      X_DOBMM_R = "CHILD COMPOSITE DOB MONTH - REVISED"
      X_DOBYY_R = "CHILD COMPOSITE DOB YEAR - REVISED"
      X_RACETH_R = "CHILD RACE PARENT AND SCHL REPORT - REV"
      X1LOCALE = "X1 LOCATION TYPE OF SCHOOL"
      X2LOCALE = "X2 LOCATION TYPE OF SCHOOL"
      X3LOCALE = "X3 LOCATION TYPE OF SCHOOL"
      X4LOCALE = "X4 LOCATION TYPE OF SCHOOL"
      X5LOCALE = "X5 LOCATION TYPE OF SCHOOL"
      X6LOCALE = "X6 LOCATION TYPE OF SCHOOL"
      X7LOCALE = "X7 LOCATION TYPE OF SCHOOL"
      X8LOCALE = "X8 LOCATION TYPE OF SCHOOL"
      X9LOCALE = "X9 LOCATION TYPE OF SCHOOL"
      X1REGION = "X1 CENSUS REGION OF SCHOOL"
      X2REGION = "X2 CENSUS REGION OF SCHOOL"
      X3REGION = "X3 CENSUS REGION OF SCHOOL"
      X4REGION = "X4 CENSUS REGION OF SCHOOL"
      X5REGION = "X5 CENSUS REGION OF SCHOOL"
      X6REGION = "X6 CENSUS REGION OF SCHOOL"
      X7REGION = "X7 CENSUS REGION OF SCHOOL"
      X8REGION = "X8 CENSUS REGION OF SCHOOL"
      X9REGION = "X9 CENSUS REGION OF SCHOOL"
      X9SESL_I = "X9 CONTINUOUS SES MEASURE (IMPUTED)"
      X1PUBPRI = "X1 PUBLIC OR PRIVATE SCHOOL"
      X2PUBPRI = "X2 PUBLIC OR PRIVATE SCHOOL"
      X3PUBPRI = "X3 PUBLIC OR PRIVATE SCHOOL"
      X4PUBPRI = "X4 PUBLIC OR PRIVATE SCHOOL"
      X5PUBPRI = "X5 PUBLIC OR PRIVATE SCHOOL"
      X6PUBPRI = "X6 PUBLIC OR PRIVATE SCHOOL"
      X7PUBPRI = "X7 PUBLIC OR PRIVATE SCHOOL"
      X8PUBPRI = "X8 PUBLIC OR PRIVATE SCHOOL"
      X9PUBPRI = "X9 PUBLIC OR PRIVATE SCHOOL"
      X1KSCTYP = "X1 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X2KSCTYP = "X2 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X4SCTYP = "X4 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X6SCTYP = "X6 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X7SCTYP = "X7 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X8SCTYP = "X8 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X9SCTYP = "X9 SCHOOL TYPE FROM THE SCH ADMIN QUEST"
      X9ASMTST = "X9 ASSESSMENT STATUS SPRING 2016"
      ;

/* format
      T9MCLASS   $LINKMF.
      T9RCLASS   $LINKR9F.
      T9SCLASS   $LINKS9F.
      D2T_ID   $PUF300F.
      D4T_ID   $PUF300F.
      PSUID   $PUF300F.
      T1_ID   $PUF300F.
      T2_ID   $PUF300F.
      T3_ID   $PUF300F.
      T4_ID   $PUF300F.
      X9ATTMCQ   _9F.
      X9INTMCQ   _9F.
      X9MSCALK5   _9F.
      X9RSCALK5   _9F.
      X9SESL_I   _9F.
      X9SSCALK5   _9F.
      X9TCHAPP   _9F.
      X9TCHCON   _9F.
      X9TCHEXT   _9F.
      X9TCHINT   _9F.
      X9TCHPER   _9F.
      X_DOBYY_R   PUF129F.
      X1LOCALE   PUF130F.
      X2LOCALE   PUF132F.
      X3LOCALE   PUF134F.
      X4LOCALE   PUF137F.
      X5LOCALE   PUF137F.
      X6LOCALE   PUF137F.
      X7LOCALE   PUF137F.
      X8LOCALE   PUF137F.
      X9LOCALE   PUF137F.
      D6T_ID   PUF146F.
      D7T_ID   PUF146F.
      D8T_ID   PUF146F.
      D9T_ID   PUF146F.
      T5_ID   PUF146F.
      T6_ID   PUF146F.
      T7_ID   PUF146F.
      T8M_ID   PUF146F.
      T8R_ID   PUF146F.
      T8S_ID   PUF146F.
      T9M_ID   PUF146F.
      T9R_ID   PUF146F.
      T9S_ID   PUF146F.
      X1REGION   PUF146F.
      X2REGION   PUF146F.
      X3REGION   PUF146F.
      X4REGION   PUF146F.
      X5REGION   PUF146F.
      X6REGION   PUF146F.
      X7REGION   PUF146F.
      X8REGION   PUF146F.
      X9EXDIS   PUF146F.
      X9REGION   PUF146F.
      X9ASMTST   PUF242F.
      X_CHSEX_R   X_CHSEX.
      X_DOBMM_R   X_DOBMM.
      X_RACETH_R   X12RACTH.
      X1KSCTYP   X1KSCTYP.
      X4SCTYP   X1KSCTYP.
      X6SCTYP   X1KSCTYP.
      X7SCTYP   X1KSCTYP.
      X8SCTYP   X1KSCTYP.
      X9SCTYP   X1KSCTYP.
      X1PUBPRI   X1PUBPRI.
      X9MTHFLG   X1RDGFLG.
      X9RDGFLG   X1RDGFLG.
      X9SCIFLG   X1RDGFLG.
      X2KSCTYP   X2KSCTYP.
      X2PUBPRI   X2PUBPRI.
      X3PUBPRI   X2PUBPRI.
      X5PUBPRI   X2PUBPRI.
      X4PUBPRI   X4PUBPRI.
      X6PUBPRI   X4PUBPRI.
      X7PUBPRI   X4PUBPRI.
      X8PUBPRI   X4PUBPRI.
      X9PUBPRI   X4PUBPRI.
      X9MTOFLG   X9OUTLIER.
      X9RTOFLG   X9OUTLIER.
      X9STOFLG   X9OUTLIER.
      ;
 */

run;

/*
proc contents;
run;

proc freq;
table 
      PSUID   
      T1_ID   
      T2_ID   
      T3_ID   
      T4_ID   
      T5_ID   
      T6_ID   
      T7_ID   
      T8R_ID   
      T8RCLASS   
      T8M_ID   
      T8MCLASS   
      T8S_ID   
      T8SCLASS   
      T9R_ID   
      T9RCLASS   
      T9M_ID   
      T9MCLASS   
      T9S_ID   
      T9SCLASS   
      D2T_ID   
      D4T_ID   
      D6T_ID   
      D7T_ID   
      D8T_ID   
      D9T_ID   
      X9RDGFLG   
      X9RTOFLG   
      X9MTHFLG   
      X9MTOFLG   
      X9SCIFLG   
      X9STOFLG   
      X9EXDIS   
      X_CHSEX_R   
      X_DOBMM_R   
      X_DOBYY_R   
      X_RACETH_R   
      X1LOCALE   
      X2LOCALE   
      X3LOCALE   
      X4LOCALE   
      X5LOCALE   
      X6LOCALE   
      X7LOCALE   
      X8LOCALE   
      X9LOCALE   
      X1REGION   
      X2REGION   
      X3REGION   
      X4REGION   
      X5REGION   
      X6REGION   
      X7REGION   
      X8REGION   
      X9REGION   
      X1PUBPRI   
      X2PUBPRI   
      X3PUBPRI   
      X4PUBPRI   
      X5PUBPRI   
      X6PUBPRI   
      X7PUBPRI   
      X8PUBPRI   
      X9PUBPRI   
      X1KSCTYP   
      X2KSCTYP   
      X4SCTYP   
      X6SCTYP   
      X7SCTYP   
      X8SCTYP   
      X9SCTYP   
      X9ASMTST   
;
run;

proc means;
var 
      X9RSCALK5   
      X9MSCALK5   
      X9SSCALK5   
      X9TCHAPP   
      X9TCHCON   
      X9TCHPER   
      X9TCHEXT   
      X9TCHINT   
      X9ATTMCQ   
      X9INTMCQ   
      X9SESL_I   
;
run;
 */

